### ISSUE TITLE
In the latest beta release, the plugin doesn't seem to work anymore.

### ISSUE THREAD

**Issue by SUN-SZY** [marc0l92/joplin-plugin-drawio#17] opened 2022-11-18 15:35 UTC
In the latest beta release, the plugin doesn't seem to work anymore. The plugin list is turned on normally, but the plugin is not running.

**Comment by jeffshead** [comment] 2022-12-19 00:02
Does not work with v2.9.17.

**Comment by nishizhen** [comment] 2022-12-21 15:35
in the joplin log:
```
2022-12-21 18:56:08: joplin.plugins: "Uncaught exception in plugin "com.github.marc0l92.joplin-plugin-drawio":", "Error: ENOENT: no such file or directory, stat '/var/folders/c_/c8d_tcln1bd2smdyzlry1bxh0000gn/T/joplin-drawio-plugin/'
Error: ENOENT: no such file or directory, stat '/var/folders/c_/c8d_tcln1bd2smdyzlry1bxh0000gn/T/joplin-drawio-plugin/'
    at statSync (node:fs:1538:3)
    at e.statSync (node:electron/js2c/asar_bundle:5:4539)
    at __node_internal_ (node:internal/fs/utils:793:8)
    at Object.rmdirSync (node:fs:1156:15)
    at t.clearDiskCache (file:///Users/nishizhen/.config/joplin-desktop/tmp/plugin_com.github.marc0l92.joplin-plugin-drawio.js:1:4250)
    at file:///Users/nishizhen/.config/joplin-desktop/tmp/plugin_com.github.marc0l92.joplin-plugin-drawio.js:1:9886
    at Generator.next (<anonymous>)
    at file:///Users/nishizhen/.config/joplin-desktop/tmp/plugin_com.github.marc0l92.joplin-plugin-drawio.js:1:9465
    at new Promise (<anonymous>)
    at n (file:///Users/nishizhen/.config/joplin-desktop/tmp/plugin_com.github.marc0l92.joplin-plugin-drawio.js:1:9210)"
2022-12-21 18:56:08: joplin.plugins: "Finished running onStart handler: com.github.marc0l92.joplin-plugin-drawio (Took 506ms)"
```

**Comment by mthii** [comment] 2022-12-30 04:05
latest joplin-2.10.2.AppImage works fine. I don't know why.

**Comment by jeffshead** [comment] 2022-12-30 11:47
> latest joplin-{2.10.2, 2.8.8}.AppImage works fine. I don't know why.

Not for me on Windows v2.10.2 pre-release.

**Comment by mthii** [comment] 2022-12-30 12:02
I'm sorry, I'm using Linux(Ubuntu). According to the Joplin log, Joplin snap failed to startup the draw.io plugin process only on the v2.9.17. I did not try Win box yet. I'm not the developper, however I was looking for the problem, but I did not find the wrong lines.

**Comment by mthii** [comment] 2023-01-02 00:48
after a couple of days I noticed 2.10.2 seems to be a little bit unstable, no draw.io menu or menu.. I'm sorry. I have changed to 2.8.8 snap.

**Comment by roblthegreat** [comment] 2023-01-04 12:57
I am experiencing the same issue running under pop_OS 22.04 and Joplin 2.9.17  I tried the appimage, the Pop!_Shop app store version, and using the install script listed as the "preferred" way to install on Linux.   Log except included below.

```
2023-01-04 06:05:22: joplin.plugins: "Uncaught exception in plugin "com.github.marc0l92.joplin-plugin-drawio":", "Error: ENOENT: no such file or directory, stat '/tmp/joplin-drawio-plugin/'
Error: ENOENT: no such file or directory, stat '/tmp/joplin-drawio-plugin/'
    at statSync (node:fs:1538:3)
    at e.statSync (node:electron/js2c/asar_bundle:5:4539)
    at __node_internal_ (node:internal/fs/utils:793:8)
    at Object.rmdirSync (node:fs:1156:15)
    at t.clearDiskCache (file:///home/robert/.config/joplin-desktop/tmp/plugin_com.github.marc0l92.joplin-plugin-drawio.js:1:4250)
    at file:///home/robert/.config/joplin-desktop/tmp/plugin_com.github.marc0l92.joplin-plugin-drawio.js:1:9886
    at Generator.next (<anonymous>)
    at file:///home/robert/.config/joplin-desktop/tmp/plugin_com.github.marc0l92.joplin-plugin-drawio.js:1:9465
    at new Promise (<anonymous>)
    at n (file:///home/robert/.config/joplin-desktop/tmp/plugin_com.github.marc0l92.joplin-plugin-drawio.js:1:9210)"
2023-01-04 06:05:22: joplin.plugins: "Finished running onStart handler: com.github.marc0l92.joplin-plugin-drawio (Took 675ms)"
```

I also tried the latest Joplin pre-release 2.10.3 applmage and it behaves the same.

**Comment by lommes** [comment] 2023-01-27 20:38
Using Joplin 2.9.17 on linux I had to create the directory /tmp/joplin-drawio-plugin/ manually and restart Joplin. After that the plugin seems to work without any problems. I don't know if the problem with windows might be related but it should be easy to look for something like posted above in the developer tools

**Comment by mthii** [comment] 2023-01-28 01:09
I confirmed it on Joplin-2.10.4.AppImage. And this is the reason why Joplin works or not works after swithcing the joplin version. Anyway we have to create the folder manually when the os restarts after using 2.8.8. This issue occurs on Mac. Maybe they are the same Joplin issue not plugins. Now joplin has the many file open errors on the log.

**Comment by tangme** [comment] 2023-01-28 03:16
today I update to 2.9.17 on window os，and then first time install draw.io。
no draw.io menu , seems not work.

**Comment by mthii** [comment] 2023-01-30 01:50
Does this issue come from these lines ?
joplin-plugin-drawio/src/resources.ts:
     28 export function clearDiskCache(): void {
     29     fs.rmdirSync(Config.TempFolder, { recursive: true })
     30     fs.mkdirSync(Config.TempFolder, { recursive: true })
     31 }
At the os starting up tmp folder might not exist...

**Comment by uvass** [comment] 2023-02-05 20:33
Thanks for the hints. I solved the issue with Joplin version 2.9.17 on my Mac by doing the following:

- Open Joplin. 
- Go to Help -> Open profile directory
- Open the log.txt
- Find the lines:
joplin.plugins: "Starting plugin: com.github.marc0l92.joplin-plugin-drawio"
2023-02-05 15:12:50: joplin.plugins: "Uncaught exception in plugin "com.github.marc0l92.joplin-plugin-drawio":", "Error: ENOENT: no such file or directory, stat '/var/folders/13/xrs38yws23lgkh5nyllg60d00000gn/T/joplin-drawio-plugin/'
Error: ENOENT: no such file or directory, stat '/var/folders/13/xrs38yws23lgkh5nyllg60d00000gn/T/joplin-drawio-plugin/'

The directory **joplin-drawio-plugin** was missing. I created it manually and restarted Joplin. 
Now Draw.io is in the "Tools" menu of Joplin.
Works like a charm.

**Comment by martin-77** [comment] 2023-02-08 12:35
> 

same here with latest version, but fix does not work. the folder gets deleted on restart of joplin

Where did you made the folder?

By the Way, i am using my own server to sync, do not know if this is relevant...

**Comment by mthii** [comment] 2023-02-08 13:30
It depends on the OS. 
- Open Joplin.
- Go to Help -> Open profile directory
- Open the log.txt, Find the lines(ENOENT), it was the folder brought the issue.
But it is just the tentative solution.

**Comment by hjstrauss** [comment] 2023-02-20 15:27
works for me on Win 10, even after new start of Joplin (2.10.6)

**Comment by xeden3** [comment] 2023-02-21 02:25
see 👍  https://github.com/marc0l92/joplin-plugin-drawio/pull/20

**Comment by 3ter** [comment] 2023-03-11 07:09
@xeden3 Shouldn't this be closed as your PR fixed the issue?
@marc0l92 There should be another release because this issue has now been fixed. I suppose it would be great to grant (one of the contributors) the respective rights to create them, so you don't have to do it.

**Comment by SUN-SZY** [comment] 2023-03-11 07:10
你好，您发的信息我已收到，尽快给你回复。

**Closed** 2023-03-11 08:03 UTC
